### ISSUE TITLE
Building on Fedora 26

### ISSUE THREAD

**Issue by bkmgit** [ohm314/forthreads#2]
Thanks for the nice library. Am building it on Fedora 26. With the current settings, the library builds with gcc 7.2.1 and gfortran 7.2.1 but the third test case fails when the flag -D_DARWIN is used. After commenting out lines 319, 320, 321 and 323 in forthread.c the third test case passes. -D_DARWIN seems to be needed for getting it to run. The pthreads library used is npth (https://www.gnupg.org/software/npth/index.html) rather than pth (https://www.gnu.org/software/pth/pth-manual.html) which seems to be less used at the moment. What was your original setup for the library?

**Comment by ohm314** [comment]
Thanks, @bkmgit !
The _DARWIN macro is used for macos, which was my development system. I did, however, test the library quite extensively on Linux. But since I haven't been updating it recently it's very well possible that some things changed. I can try to take a look into it in the next week or so. If you find a good fix please feel free to share it, though.

**Comment by ohm314** [comment]
Alright, I finally had a chance to look into those compilation issues. I found actually several fixes which are needed to make the library compatible with macos (Darwin) and linux and all the tests pass. Please give it a try and let me know (if you are compiling on Fedora, make sure __DARWIN is _not_ set.

**Comment by ohm314** [comment]
I'll close the ticket for now. If you find another issue, please feel free to reopen the ticket!
